### ISSUE TITLE
Warning: GetDeveroomTagForCaret: Snapshot version mismatch

### ISSUE THREAD

**Issue by kadamgreene** [SpecFlowOSS/SpecFlow.VisualStudio#199] opened 2021-11-11 15:16 UTC
### Used Visual Studio

Visual Studio 2019

### Are the latest Visual Studio updates installed?

Yes

### SpecFlow Section in app.config or content of specflow.json

{
	"language": {
		"feature": "en"
	}
}

### Issue Description

**Note:**  This is actually for VS2022

When typing:
```
When I fill fields
| Accept | Age |
| true   | 
```

And when I finish the table:
```
When I fill fields
| Accept | Age |
| true   | 20  |
```
it suddenly opens the Specflow output window, changes focus to it, and writes:
```
Warning: GetDeveroomTagForCaret: Snapshot version mismatch
```

### Steps to Reproduce

See description

**Comment by gasparnagy** [comment] 2021-11-12 07:15
@kadamgreene Besides the annoying warning sign, did you notice anything else (was it working correctly otherwise)? Does this happen often and is it reproducible (not on my side)?

**Comment by tparikka** [comment] 2021-11-18 22:32
I am encountering this in Visual Studio 2022 with the new extension for that version. It's quite annoying since it captures focus and breaks typing flow. It doesn't appear to break functionality, but it is very disruptive.

**Comment by kadamgreene** [comment] 2021-11-19 03:54
@gasparnagy It happens quite a bit in Visual Studio 2022 as @tparikka has indicated, it steals focus and breaks typing flow.  The editor seems to be working fine otherwise.

**Comment by gasparnagy** [comment] 2021-11-19 12:55
@tparikka @kadamgreene: OK/thx. That's a good input. 

@patiqs: We probably just need to change the severity of this message from Warning to Debug log. 

@tparikka @kadamgreene: If you want to try yourself, you could also try to apply this change and submit a PR to https://github.com/SpecFlowOSS/SpecFlow.VS.

**Comment by tparikka** [comment] 2021-11-20 16:41
@gasparnagy I replied in the issue in the other repo with some thoughts and a question. @kadamgreene can you confirm this issue is only happening in VS 2019 or lower for you? I think this repo may only be used for 2019 and previous extensions based on the comments here, also the fact that I can't find the problematic method in this repo. If so, we should close this issue and move it over to https://github.com/SpecFlowOSS/SpecFlow.VS.

**Comment by gasparnagy** [comment] 2021-11-22 10:14
The `GetDeveroomTagForCaret` method and the snapshot version verification has been introduced in the VS2022 extension (https://github.com/SpecFlowOSS/SpecFlow.VS) so this issue surely happened in VS2022 also for @kadamgreene. 

So I think I will close this issue for now and let's continue the discussion at the other issue @tparikka linked.

**Closed** 2021-11-22 10:45 UTC
